---
apiVersion: v1
kind: Service
metadata:
  name: stock-service
  labels:
    name: vlingo-stock-service-0.1.0
    app.kubernetes.io/name: vlingo-stock-service
    app.kubernetes.io/instance: vss-01
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: vlingo-stock-service
    app.kubernetes.io/instance: vss-01
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-service
  labels:
    name: vlingo-stock-service-0.1.0
    app.kubernetes.io/name: vlingo-stock-service
    app.kubernetes.io/instance: vss-01
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vlingo-stock-service
      app.kubernetes.io/instance: vss-01
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vlingo-stock-service
        app.kubernetes.io/instance: vss-01
    spec:
      securityContext:
        {}
      containers:
        - env:
            - name: SERVER_PORT
              value: "8081"
            - name: STOCK_SERVICE_DATABASE_URL
              value: "jdbc:postgresql://stock-database-service:5432/postgres"
            - name: MESSAGING_URI
              value: "amqp://guest:guest@rabbitmq-service:5672"
          image: dambrosio/vlingo-stock-service:latest
          name: vlingo-stock-service
          ports:
            - containerPort: 8081
              name: http

