language: java
dist: trusty

before_install:
  - rm -rf $HOME/.m2/repository/io/vlingo

script:
  - mvn clean test -U

before_cache:
  - rm -rf $HOME/.m2/repository/io/vlingo
cache:
  directories:
    - $HOME/.m2/repository
