version: '3'
services:
  front:
    build: ./xoom-http-frontservice
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - back
  back:
    build: ./xoom-http-backservice
    restart: always
