apiVersion: v1
kind: Service
metadata:
  name: app2host # acts as DNS!
  namespace: xoom-space
spec:
  type: NodePort # switch to ClusterIP afterwards
  selector:
    tier: application
    appName: pod-node2
  ports:
    - name: operational
      protocol: TCP
      port: 17373
      targetPort: 17373
    - name: application
      protocol: TCP
      port: 17374
      targetPort: 17374
    - name: debug # to be removed
      protocol: TCP
      targetPort: 5070
      port: 5072
      nodePort: 30572 # debugging port for IDE
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-node2
  namespace: xoom-space
  labels:
    appName: deployment-node2
spec:
  selector:
    matchLabels:
      tier: application
      appName: pod-node2
  template:
    metadata:
      labels:
        tier: application
        appName: pod-node2
    spec:
      containers:
        - name: node2-app
          image: vlingo/example-cqrs:1.0
          ports:
          - name: operational
            containerPort: 17373
          - name: application
            containerPort: 17374
          - name: debug # to be removed
            containerPort: 5070
          env:
          - name: APP_ARGS
            value: node2
