apiVersion: v1
kind: Service
metadata:
  name: app1host # acts as DNS!
  namespace: xoom-space
spec:
  type: NodePort # switch to ClusterIP afterwards
  selector:
    tier: application
    appName: pod-node1
  ports:
    - name: operational
      protocol: TCP
      port: 17371
      targetPort: 17371
    - name: application
      protocol: TCP
      port: 17372
      targetPort: 17372
    - name: http # HTTP port
      protocol: TCP
      targetPort: 18080
      port: 18080
      nodePort: 30080
    - name: debug # to be removed
      protocol: TCP
      targetPort: 5070
      port: 5071
      nodePort: 30571 # debugging port for IDE
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-node1
  namespace: xoom-space
  labels:
    appName: deployment-node1
spec:
  selector:
    matchLabels:
      tier: application
      appName: pod-node1
  template:
    metadata:
      labels:
        tier: application
        appName: pod-node1
    spec:
      containers:
        - name: node1-app
          image: vlingo/example-cqrs:1.0
          ports:
          - name: operational
            containerPort: 17371
          - name: application
            containerPort: 17372
          - name: http
            containerPort: 18080
          - name: debug # to be removed
            containerPort: 5070
          env:
          - name: APP_ARGS
            value: node1
