apiVersion: v1
kind: Service
metadata:
  name: {{ include "vlingo-stock-database.serviceAccountName" . }}
  labels:
    {{- include "vlingo-stock-database.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
  selector:
    {{- include "vlingo-stock-database.selectorLabels" . | nindent 4 }}
