application:
  name: "demo-application"
server:
  port: 8080
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/
    driverClassName: org.postgresql.Driver
    username: dbuser
    password: theSecretPassword
    schema-generate: CREATE_DROP
    dialect: POSTGRES
jpa:
  default:
    properties:
      hibernate:
        bytecode:
          provider: none
        hbm2ddl:
          auto: update