apiVersion: apps/v1
kind: Deployment
metadata:
  name: vlingo-cluster
  labels:
    name: vlingo-cluster-0.1.0
    app.kubernetes.io/name: vlingo-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vlingo-cluster
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vlingo-cluster
    spec:
      securityContext:
        {}
      containers:
      - name: first-node
        image: dambrosio/vlingo-kubernetes-cluster:latest
        env:
          - name: NODE_NAME
            value: "node1"
        ports:
          - containerPort: 8080
            name: app
          - containerPort: 9080
            name: op
      - name: second-node
        image: dambrosio/vlingo-kubernetes-cluster:latest
        env:
          - name: NODE_NAME
            value: "node2"
        ports:
          - containerPort: 8081
            name: app
          - containerPort: 9081
            name: op
      - name: third-node
        image: dambrosio/vlingo-kubernetes-cluster:latest
        env:
          - name: NODE_NAME
            value: "node3"
        ports:
          - containerPort: 8082
            name: app
          - containerPort: 9082
            name: op