apiVersion: v1
kind: Service
metadata:
  labels:
    component: stock-postgres
  name: stock-database-service
spec:
  ports:
    - port: 5432
  selector:
    app: stock-app
    component: stock-postgres