apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    component: stock-postgres
  name: stock-postgres-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: stock-app
        component: stock-postgres
    spec:
      containers:
        - image: postgres:9.6
          name: stock-database
          ports:
            - containerPort: 5432
          resources:
            limits:
              cpu: 100m