---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    name: vlingo-order-service-0.1.0
    app.kubernetes.io/name: vlingo-order-service
    app.kubernetes.io/instance: vos-01
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: vlingo-order-service
    app.kubernetes.io/instance: vos-01
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    name: vlingo-order-service-0.1.0
    app.kubernetes.io/name: vlingo-order-service
    app.kubernetes.io/instance: vos-01
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: vlingo-order-service
      app.kubernetes.io/instance: vos-01
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vlingo-order-service
        app.kubernetes.io/instance: vos-01
    spec:
      securityContext:
        {}
      containers:
        - env:
            - name: SERVER_PORT
              value: "8080"
            - name: ORDER_SERVICE_DATABASE_URL
              value: "jdbc:postgresql://order-database-service:5432/postgres"
            - name: MESSAGING_URI
              value: "amqp://guest:guest@rabbitmq-service:5672"
          image: dambrosio/vlingo-order-service:latest
          name: vlingo-order-service
          ports:
            - containerPort: 8080
              name: http
