apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-service
spec:
  replicas: 1
  selector:
    matchLabels:
      name: stock-service
  template:
    metadata:
      labels:
        name: stock-service
    spec:
      containers:
      - env:
        - name: SERVER_PORT
          value: "8081"
        - name: STOCK_SERVICE_DATABASE_URL
          value: "jdbc:postgresql://stock-database-service:5432/postgres"
        - name: MESSAGING_URI
          value: "amqp://guest:guest@rabbitmq-service:5672"
        image: dambrosio/vlingo-stock-service:latest
        name: vlingo-stock-service
        ports:
          - containerPort: 8081
      restartPolicy: Always