version: "3.7"

services:
  account-service:
    image: "vlingo/account-service:latest"
    environment:
      - SERVER_PORT=8080
      - EUREKA_HOST=discovery-service
      - EUREKA_CLIENT_REGISTRATION_PREFER_IP_ADDRESS=true
    links:
      - discovery-service
    networks:
      - microservice

  discovery-service:
    image: "vlingo/discovery-service:latest"
    ports:
      - "8761:8761"
    expose:
      - "8761"
    networks:
      - microservice

  api-gateway:
    image: "vlingo/api-gateway:latest"
    ports:
      - "9000:9000"
    expose:
      - "9000"
    environment:
      - EUREKA_HOST=discovery-service
    links:
      - discovery-service
      - account-service
    networks:
      - microservice

networks:
  microservice:
