apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    component: order-postgres
  name: order-postgres-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: order-app
        component: order-postgres
    spec:
      containers:
        - image: postgres:9.6
          name: order-database
          ports:
            - containerPort: 5432
          resources:
            limits:
              cpu: 100m