version: '3.1'

services:
  postgres:
    image: postgres:latest
    volumes:
       - vlingo_cars_postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: vlingodb
      POSTGRES_USER: vlingo_test
      POSTGRES_PASSWORD: vlingo123

volumes:
  vlingo_cars_postgres:
